export const ROUTES = {
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  dashboard: '/dashboard',
  trips: '/trips',
  tripNew: '/trips/new',
  trip: (id) => `/trips/${id}`,
  tripEdit: (id) => `/trips/${id}/edit`,
  tripItinerary: (id) => `/trips/${id}/itinerary`,
  tripCalendar: (id) => `/trips/${id}/calendar`,
  tripBudget: (id) => `/trips/${id}/budget`,
  discover: '/discover',
  discoverCities: '/discover/cities',
  city: (id) => `/discover/cities/${id}`,
  discoverTrips: '/discover/trips',
  sharedTrip: (id) => `/shared/${id}`,
  profile: '/profile',
  settings: '/settings',
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
}
